    - name: Systemd service
      template:
        src: app.unit.j2
        dest: /etc/systemd/system/app.service
      when: "ansible_service_mgr == 'systemd'" 
      register: service_conf

    - name: restart service
      service:
        name: app
        state: restarted
      when: service_conf.changed
