---

- name: "Ensure Nginx default server symlink is absent"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: "absent"

- name: "Add managed vhost config file"
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/nginx.conf
    force: true
    owner: root
    mode: 0644
  notify: reload nginx


